### ISSUE TITLE
Add cancellation action

### ISSUE THREAD

**Issue by arieswandari** [janosgyerik/jquery-upvote#7] opened 2015-02-23 06:43 UTC
Is there any way to cancel action. Currently, I do cancellation by doing re-initialization and set the callback again.

**Comment by janosgyerik** [comment] 2015-03-19 23:04
What exactly would you like to cancel? The buttons work as toggles, click again to flip the state. I'm not sure what behavior you're looking for.

**Comment by arieswandari** [comment] 2015-03-25 15:36
I mean cancelling action without clicking. E.g user doing votes up, but backend process said its not valid and need to be cancelled (automatically,without clicking the button).

**Comment by janosgyerik** [comment] 2016-08-03 18:22
Duplicate of #5

**Closed by janosgyerik** 2016-08-03 18:22 UTC
